# Generated by Django 5.1.3 on 2024-11-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockQuery',
            new_name='StockCache',
        ),
    ]
